server:
  port: 8086

spring:
  application:
    name: service-product-consumer-fegin-hystrix

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#开启断路器
feign:
  hystrix:
    enabled: true

# 负载均衡配置为随机,不配置默认轮询
service-user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

